//By Carson Rueber
using UnityEngine;
using System.Collections.Generic;
using System.IO;

//Loads the passenger data matrix generated by lua
//Should consider turning this into a static thing
public class AirportData {
	private TravelInfo[,] data;
	private Dictionary<string, int> lookupTable;

	//Contains travel info for an aiport to another airport
	public struct TravelInfo {
		public int distance;
		public int personsPerYear;
	}

	public AirportData() {
		init();
	}

	public TravelInfo getInfo(string origin, string dest) {
		int originInt = lookupTable[origin];
		int destInt = lookupTable[dest];
		return data[originInt, destInt];
	}

	public int getDistance(string origin, string dest) {
		int originInt = lookupTable[origin];
		int destInt = lookupTable[dest];
		return data[originInt, destInt].distance;
	}

	public int getDistance(int origin, int dest) {
		return data[origin, dest].distance;
	}

	public int getIdFromCode(string code) {
		return lookupTable[code];
	}

	public void init() {
		TextReader textReader = File.OpenText(DataHandler.aiportMatrixFilepath);
		string[] firstLineBits = textReader.ReadLine().Split(' ');

		data = new int[firstLineBits.Length - 1, firstLineBits.Length - 1];
		lookupTable = new Dictionary<string, int>(firstLineBits.Length - 1);

		//Set the 3 letter code to point to an index from 0 - whatever
		for (int q = 1; q < firstLineBits.Length; q++) {
			lookupTable[firstLineBits[q]] = q - 1;
		}


		while (true) {
			string line = textReader.ReadLine();
			if (line == null) break;
			string[] lineBits = line.Split(' ');
			string originCode = lineBits[0];
			int originInt = lookupTable[originCode];
			for (int q = 1; q < lineBits.Length; q++) {
				string destCode = firstLineBits[q];
				int value = int.Parse(lineBits[q]);
				
				data[originInt, lookupTable[destCode]] = value;
			}
		}
	}
}